CREATE TABLE YCSBSPARSE (
	YCSB_KEY INT,
	FIELD0 TEXT null, FIELD1 TEXT null,
	FIELD2 TEXT null, FIELD3 TEXT null,
	FIELD4 TEXT null, FIELD5 TEXT null,
	FIELD6 TEXT null, FIELD7 TEXT null,
	FIELD8 TEXT null, FIELD9 TEXT null,
	PRIMARY KEY (YCSB_KEY)
)
go
