snapshot:
  threads: 1
  _traceDBTasks: true
  fetch-user-roles: false
  _fetch-exact-row-count: false    
    
  min-job-size-rows: 100_000 # default 1_000_000 is too large for purposes demo
  ddl-replication:
    enable: true

realtime:
  threads: 1
  _traceDBTasks: true
  # enable DDL replication
  ddl-replication:
    enable: true
    catalog: arcsrc
    schema:  dbo
    detect-ddl-interval: 1   # default 600 is too long for demo wait
    ddl-replication-mode: INLINE # Default is REINIT mode. [REINIT|INLINE]
  # replicate_io_cdc_heartbeat table at arcsrc database instead of default io_replication 
  heartbeat:
    enable: false
    catalog: arcsrc
    schema: dbo
    table-name : REPLICATE_IO_CDC_HEARTBEAT


